jwt:
  secretKey: asdfBbsXfjh23j1313415hbajshSDbaepitwerSdjsaUhfbj2h42353464

  access:
    expiration: 315360000000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) = 3600000)이 아니라 10년으로 변경함
    header: Authorization

  refresh:
    expiration: 315360000000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주) = 1209600000)이 아니라 10년으로 변경함
    header: Authorization-refresh